version: 2
updates:
  - package-ecosystem: docker
    directories:
      - /packaging/docker/alpine
      - /packaging/docker/alpine-k8s
      - /packaging/docker/sidecar
      - /packaging/docker/ubuntu-20.04
      - /packaging/docker/ubuntu-22.04
      - /packaging/docker/ubuntu-24.04
    schedule:
      interval: weekly
    groups:
      container-images:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      otel:
        patterns:
          - go.opentelemetry.io/*
      golang-x:
        patterns:
          - golang.org/x/*
      cloud-providers:
        patterns:
          - github.com/Azure/*
          - github.com/aws/*
          - google.golang.org/*
